[package]
name = "zaku"
version = "0.2.0"
description = "Fast, open-source API client with fangs"
license = "MIT"
authors = ["Mayank Verma <errmayank@gmail.com>"]
repository = "https://github.com/buildzaku/zaku"
homepage = "https://zaku.app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.0.1", features = [] }

[dependencies]
dirs = { version = "=5.0.1" }
once_cell = { version = "=1.20.2" }
postcard = { version = "=1.0.10", features = ["use-std"] }
serde = { version = "=1.0.210", features = ["derive"] }
serde_json = { version = "=1.0.128" }
tauri = { version = "=2.0.3", features = ["devtools"] }
tauri-plugin-dialog = { version = "=2.0.1" }
tauri-plugin-global-shortcut = { version = "=2.0.1" }
tauri-plugin-http = { version = "=2.0.1" }
tauri-plugin-notification = { version = "=2.0.1" }
toml = { version = "=0.8.19", features = ["preserve_order"] }
ts-rs = { version = "=10.0.0" }

[target.'cfg(target_os = "linux")'.dependencies]
wgpu = { version = "=22.1.0", default-features = false }
