[package]
name = "zaku"
version = "0.1.0"
description = "Fast, open-source API client with fangs"
license = "MIT"
authors = ["Mayank Verma <errmayank@gmail.com>"]
repository = "https://github.com/buildzaku/zaku"
homepage = "https://zaku.app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.0.0-rc.3", features = [] }

[dependencies]
serde = { version = "=1.0.203", features = ["derive"] }
serde_json = { version = "=1.0.117" }
tauri = { version = "=2.0.0-rc.3", features = ["devtools"] }
tauri-plugin-dialog = { version = "=2.0.0-rc.1" }
tauri-plugin-global-shortcut = { version = "=2.0.0-rc.1" }
tauri-plugin-http = { version = "=2.0.0-rc.0" }
tauri-plugin-notification = { version = "=2.0.0-rc.1" }
tauri-plugin-store = { version = "=2.0.0-rc.1" }
toml = { version = "=0.8.17" }
