[package]
name = "app_version"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "app_version"
path = "src/app_version.rs"

[[bin]]
name = "version"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
jiff = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
