[changelog]
body = """{% for group, commits in commits | group_by(attribute="group") -%}
{% if not loop.first %}
{% endif -%}
### {{ group | striptags | trim | upper_first }}

{% for commit in commits -%}
    - {{ commit.message | upper_first }} - [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/buildzaku/zaku/commit/{{ commit.id }})
{% endfor %}
{%- endfor %}"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
    { message = "^feat!", group = "<!-- 0 -->Breaking Changes" },
    { message = "^feat", group = "<!-- 1 -->Features" },
    { message = "^fix", group = "<!-- 2 -->Bug Fixes" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^ui", group = "<!-- 4 -->UI/UX" },
    { message = "^ux", group = "<!-- 4 -->UI/UX" },
    { message = "^refactor", group = "<!-- 5 -->Refactor" },
    { message = "^docs", group = "<!-- 6 -->Documentation" },
    { message = "^test", group = "<!-- 7 -->Testing" },
    { message = "^revert", group = "<!-- 8 -->Reverts" },
    { message = "^release", skip = true },
    { message = "^style", skip = true },
    { message = "^ci", skip = true },
    { message = "^chore", skip = true },
    { message = "^build", skip = true },
]

protect_breaking_commits = true
filter_commits = false
tag_pattern = "[0-9]+\\.[0-9]+\\.[0-9]+"
topo_order = false
sort_commits = "oldest"
