[changelog]
body = """{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group | striptags | trim | upper_first }}

{% for commit in commits -%}
    - {{ commit.message | upper_first }} - [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/buildzaku/zaku/commit/{{ commit.id }})
{% endfor -%}
{% endfor -%}"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
    { message = "^feat!", group = "BREAKING CHANGES" },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^ui", group = "UI" },
    { message = "^ux", group = "UX" },
    { message = "^docs", group = "Documentation" },
    { message = "^refactor", group = "Refactor" },
    { message = "^release", skip = true },
    { message = "^style", skip = true },
    { message = "^test", skip = true },
    { message = "^ci", skip = true },
    { message = "^chore", skip = true },
    { message = "^build", skip = true },
    { message = "^revert", skip = true },
]

protect_breaking_commits = true
filter_commits = false
tag_pattern = "[0-9]+\\.[0-9]+\\.[0-9]+"
topo_order = false
sort_commits = "oldest"
