name: zaku
base: core18
version: 0.4.0
summary: Fast, open-source API client with fangs
description: |
    Fast, open-source API client with fangs
grade: stable
confinement: strict
architectures:
    - amd64
parts:
    zaku-amd64:
        plugin: dump
        source: https://github.com/buildzaku/zaku/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Zaku_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
        source-type: deb
        organize:
            usr/bin/zaku: usr/bin/zaku-amd64
apps:
    zaku-amd64:
        command: zaku-amd64
