[package]
name = "sync-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117" }
toml_edit = { version = "0.22.13" }
