[package]
name = "recent_projects"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "recent_projects"
path = "src/recent_projects.rs"

[lints]
workspace = true

[dependencies]
actions = { workspace = true }
anyhow = { workspace = true }
fs = { workspace = true }
fuzzy_nucleo = { workspace = true }
gpui = { workspace = true }
path = { workspace = true }
picker = { workspace = true }
ui = { workspace = true }
workspace = { workspace = true }
