#!/usr/bin/env bash

set -euo pipefail

if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
  echo "Bash 5.2 or later is required" >&2
  exit 1
fi

if [[ ! " $* " == *" -p "* && ! " $* " == *" --package "* ]]; then
  set -- "$@" --workspace
fi

set -x

cargo clippy "$@" --release --all-targets --all-features -- --deny warnings
