#!/usr/bin/env bash

set -euo pipefail

if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
  echo "Bash 5.2 or later is required" >&2
  exit 1
fi

package_specified=false
for argument in "$@"; do
  case "$argument" in
  -p | --package | --package=*)
    package_specified=true
    break
    ;;
  esac
done

if ! $package_specified; then
  set -- "$@" --workspace
fi

set -x

cargo clippy "$@" --release --all-targets --all-features -- --deny warnings
