#!/usr/bin/env bash

set -euo pipefail

if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
  echo "Bash 5.2 or later is required" >&2
  exit 1
fi

if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
  if [[ $# -ne 1 ]]; then
    echo "Unexpected argument: $2" >&2
    echo "Run ./script/get-version --help" >&2
    exit 1
  fi
  echo "Usage: ./script/get-version [OPTIONS]"
  echo "Print Zaku version."
  echo "Options:"
  echo "  --display   Print Zaku display version."
  echo "  -h, --help  Show help."
  exit 0
fi
if [[ $# -gt 1 ]]; then
  echo "Unexpected argument: $2" >&2
  echo "Run ./script/get-version --help" >&2
  exit 1
fi
if [[ $# -eq 1 && $1 != "--display" ]]; then
  echo "Unexpected argument: $1" >&2
  echo "Run ./script/get-version --help" >&2
  exit 1
fi

version=$(cargo metadata --no-deps --format-version=1 | jq --exit-status --raw-output '.packages[] | select(.name == "zaku") | .version')

if [[ "$version" == *+* ]]; then
  echo "Version cannot contain build metadata" >&2
  exit 1
fi

if [[ ${1:-} == "--display" && "$version" =~ ^([0-9]+)\.([0-9]+)\.0(-.+)?$ ]]; then
  echo "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
else
  echo "$version"
fi
