#!/usr/bin/env bash

set -euo pipefail

if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
  echo "Bash 5.2 or later is required" >&2
  exit 1
fi

if [[ $# -gt 0 ]]; then
  echo "Unexpected argument: $1" >&2
  exit 1
fi

version=$("${CARGO:-cargo}" metadata --no-deps --format-version=1 | jq --exit-status --raw-output '.packages[] | select(.name == "zaku") | .version')

if [[ "$version" == *+* ]]; then
  echo "Version cannot contain build metadata" >&2
  exit 1
fi

if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.0(-.+)?$ ]]; then
  echo "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
else
  echo "$version"
fi
