name = "XML"
grammar = "xml"
path_suffixes = ["xml"]
autoclose_before = ">})"
block_comment = { start = "<!--", prefix = "", end = "-->", tab_size = 0 }
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "<", end = ">", close = true, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "!--", end = " --", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
