name: "Check Style"

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ case(github.ref_name == 'main', github.sha, github.ref_name) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check_style:
    name: "Check Style"
    if: github.repository == 'buildzaku/zaku'
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Check shell scripts"
        run: ./script/check --verbose
        shell: bash

      - name: "Install PSScriptAnalyzer"
        run: Install-PSResource -Name PSScriptAnalyzer -Version 1.25.0 -Scope CurrentUser -TrustRepository
        shell: pwsh

      - name: "Check PowerShell scripts"
        run: pwsh -File ./script/check.ps1 -Verbose

      - name: "Setup pnpm"
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10.33.2

      - name: "Install shfmt"
        uses: taiki-e/install-action@91ddec75689c4c78665b598d188dc821c5a43e5c # v2.85.9
        with:
          tool: shfmt@3.13.1

      - name: "Check formatting"
        run: ./script/fmt --check
        shell: bash

      - name: "Check for typos"
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
