name: "Check Style"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check_style:
    name: "Check Style"
    if: github.repository == 'buildzaku/zaku'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: "Check Prettier formatting"
        run: ./script/prettier
        shell: bash

      - name: "Check Rust formatting"
        run: cargo fmt --all -- --check

      - name: "Check for typos"
        uses: crate-ci/typos@v1.43.1
