name: "Check Style"

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ case(github.ref_name == 'main', github.sha, github.ref_name) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check_style:
    name: "Check Style"
    if: github.repository == 'buildzaku/zaku'
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Install shell tools"
        uses: taiki-e/install-action@6c6fd71fe4fb72c3697d269963d0e15df8adedad # v2.85.10
        with:
          tool: |
            shellcheck
            shfmt

      - name: "Check shell scripts"
        run: ./script/check --verbose
        shell: bash

      - name: "Install PSScriptAnalyzer"
        run: Install-PSResource -Name PSScriptAnalyzer -Version 1.25.0 -Scope CurrentUser -TrustRepository
        shell: pwsh

      - name: "Check PowerShell scripts"
        run: ./script/check.ps1 -Verbose
        shell: pwsh

      - name: "Setup pnpm"
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          version: 11.20.0
          runtime: node@24.18.1
          install: false

      - name: "Check formatting"
        run: ./script/fmt --check
        shell: bash

      - name: "Check for typos"
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
