name: "Run Clippy"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.head_ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: "1"

jobs:
  run_clippy_linux_x86_64:
    name: "Clippy Linux x86_64"
    if: github.repository == 'buildzaku/zaku'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Install Linux dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libfontconfig-dev \
            libasound2-dev \
            libssl-dev

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

  run_clippy_macos_arm64:
    name: "Clippy macOS ARM64"
    if: github.repository == 'buildzaku/zaku'
    runs-on: macos-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

  run_clippy_macos_x86_64:
    name: "Clippy macOS x86_64"
    if: github.repository == 'buildzaku/zaku'
    runs-on: macos-15-intel
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

  run_clippy_windows_x86_64:
    name: "Clippy Windows x86_64"
    if: github.repository == 'buildzaku/zaku'
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Cargo config"
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/workflow-config.toml" -Destination "./../.cargo/config.toml"
        shell: pwsh

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: "Run Clippy"
        run: ./script/clippy.ps1
        shell: pwsh
