name: "Run Clippy"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  run_clippy_linux:
    name: "Clippy Linux"
    if: github.repository == 'buildzaku/zaku'
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Install Linux dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libfontconfig-dev \
            libasound2-dev \
            libssl-dev

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-targets: false

      - name: "Setup sccache"
        run: ./script/setup-sccache
        shell: bash
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_SCCACHE_BUCKET: ${{ secrets.R2_SCCACHE_BUCKET }}

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

      - name: "Show sccache stats"
        run: sccache --show-stats
        shell: bash

  run_clippy_macos:
    name: "Clippy macOS"
    if: github.repository == 'buildzaku/zaku'
    runs-on: macos-26
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup Cargo config"
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-targets: false

      - name: "Setup sccache"
        run: ./script/setup-sccache
        shell: bash
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_SCCACHE_BUCKET: ${{ secrets.R2_SCCACHE_BUCKET }}

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

      - name: "Show sccache stats"
        run: sccache --show-stats
        shell: bash

  run_clippy_windows:
    name: "Clippy Windows"
    if: github.repository == 'buildzaku/zaku'
    runs-on: windows-2025
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup Cargo config"
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/workflow-config.toml" -Destination "./../.cargo/config.toml"
        shell: pwsh

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-targets: false

      - name: "Setup sccache"
        run: ./script/setup-sccache.ps1
        shell: pwsh
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_SCCACHE_BUCKET: ${{ secrets.R2_SCCACHE_BUCKET }}

      - name: "Run Clippy"
        run: ./script/clippy.ps1
        shell: pwsh

      - name: "Show sccache stats"
        run: if ($env:RUSTC_WRAPPER) { & $env:RUSTC_WRAPPER --show-stats }
        shell: pwsh
