name: "Run Tests"

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ case(github.ref_name == 'main', github.sha, github.ref_name) }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  run_tests:
    name: "Test ${{ matrix.name }}"
    if: github.repository == 'buildzaku/zaku'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux ARM64"
            os: ubuntu-24.04-arm
          - name: "Linux x86_64"
            os: ubuntu-24.04
          - name: "macOS ARM64"
            os: macos-26
          - name: "macOS x86_64"
            os: macos-26-intel
          - name: "Windows ARM64"
            os: windows-11-arm
          - name: "Windows x86_64"
            os: windows-2025
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install Bash (macOS)"
        if: runner.os == 'macOS'
        run: brew install bash
        shell: bash

      - name: "Setup Cargo config (Linux and macOS)"
        if: runner.os != 'Windows'
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/workflow-config.toml ./../.cargo/config.toml
        shell: bash

      - name: "Setup Cargo config (Windows)"
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/workflow-config.toml" -Destination "./../.cargo/config.toml"
        shell: pwsh

      - name: "Install dependencies (Linux)"
        if: runner.os == 'Linux'
        run: ./script/linux
        shell: bash

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-bin: false
          cache-targets: false
          shared-key: ${{ matrix.os }}

      - name: "Install Nextest"
        uses: taiki-e/install-action@91ddec75689c4c78665b598d188dc821c5a43e5c # v2.85.9
        with:
          tool: nextest

      - name: "Setup sccache (Linux and macOS)"
        if: runner.os != 'Windows'
        run: ./script/setup-sccache
        shell: bash
        env: &sccache_env
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_SCCACHE_BUCKET: ${{ secrets.R2_SCCACHE_BUCKET }}

      - name: "Setup sccache (Windows)"
        if: runner.os == 'Windows'
        run: ./script/setup-sccache.ps1
        shell: pwsh
        env: *sccache_env

      - name: "Run tests"
        run: cargo nextest run --workspace --all-features --no-fail-fast

      - name: "Show sccache stats"
        if: env.RUSTC_WRAPPER
        run: sccache --show-stats
